### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by Feiyue-Peng** [lmb-freiburg/flownet2#60]
examples/cifar10 examples/mnist examples/cpp_classification examples/siamese matlab/+caffe/private python/caffe src/caffe src/caffe/util src/caffe/layers src/caffe/solvers src/caffe/test src/caffe/proto src/gtest tools
CXX/LD -o .build_release/tools/convert_imageset_and_disparity.bin
.build_release/tools/convert_imageset_and_disparity.o：in the function ‘debugData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)’：
convert_imageset_and_disparity.cpp:(.text+0xc07)：对‘caffe::writeFloFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float const*, int, int)’undefined reference
convert_imageset_and_disparity.cpp:(.text+0xc62)：对‘caffe::writePPM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float const*, int, int, bool, float)’undefined reference
convert_imageset_and_disparity.cpp:(.text+0xcc0)：对‘caffe::writePPM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float const*, int, int, bool, float)’undefined reference
convert_imageset_and_disparity.cpp:(.text+0xd1a)：对‘caffe::writePGM(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float const*, int, int, float)’undefined reference
collect2: error: ld returned 1 exit status
Makefile:620: recipe for target '.build_release/tools/convert_imageset_and_disparity.bin' failed
make: *** [.build_release/tools/convert_imageset_and_disparity.bin] Error 1

I encountered this problem when run 'make'. Would you please have a look at this problem?

**Comment by nikolausmayer** [comment]
Hi,

looks like your `caffe.so` wasn't compiled correctly. Do you have another Caffe installation whose paths might interfere with finding this file?

Try `make clean` and another `make` run.

Try `VERBOSE=1 make tools` and look at the paths.

Best,
 Nikolaus

**Comment by Feiyue-Peng** [comment]
I have solved this problem thanks to your advice. I have changed the path of caffe.so, but I did't realize it.
Thank you very much! 
Yours,
Peng

**Comment by lesurp** [comment]
Hi!

Bit late to the party, but I'm encountering the same issue:
```
examples/siamese examples/mnist examples/cpp_classification examples/cifar10 matlab/+caffe/private python/caffe src/gtest src/caffe src/caffe/util src/caffe/solvers src/caffe/proto src/caffe/layers src/caffe/test tools
CXX/LD -o .build_release/tools/convert_imageset_and_disparity.bin
.build_release/tools/convert_imageset_and_disparity.o: In function `debugData(std::string)':
convert_imageset_and_disparity.cpp:(.text+0xa96): undefined reference to `caffe::writeFloFile(std::string, float const*, int, int)'
convert_imageset_and_disparity.cpp:(.text+0xae4): undefined reference to `caffe::writePPM(std::string, float const*, int, int, bool, float)'
convert_imageset_and_disparity.cpp:(.text+0xb2c): undefined reference to `caffe::writePPM(std::string, float const*, int, int, bool, float)'
convert_imageset_and_disparity.cpp:(.text+0xb6e): undefined reference to `caffe::writePGM(std::string, float const*, int, int, float)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset_and_disparity.bin] Error 1
```

Funny thing, this is on a remote server - the project compiles fine on my local machine. Do you know if this should work with `g++-4.8`? This is the only difference I can come up with between the two set ups...

Edit: it seems the file `.build_release/lib/libcaffe.so` doesn't actually contain those missing symbols, strange...

**Comment by nikolausmayer** [comment]
@lesurp 
does your `libcaffe.so` contain *other* symbols for `writeFloFile` etc? It might possibly be a C++11 issue (which could then be related to your GCC version).

**Comment by lesurp** [comment]
Sorry for the waste of time, I found the problem.

There was already a system-wide caffe installation, and despite adding the directory containing the library built by this repo (`-Lbuild/lib`), it was still linking with the system `libcaffe.so`...
Quick fix was to change, in the `Makefile`, the link command to link to the `build/lib/libcaffe.so` file directly (although I managed to change my environment, so now I don't have any caffe installation)

Thanks!
