### ISSUE TITLE
[CuDNN] compilation error

### ISSUE THREAD

**Issue by Maryada-27** [lmb-freiburg/flownet2#92]
![_cudnn](https://user-images.githubusercontent.com/24396825/33232358-5ddb92c8-d205-11e7-8364-427a4af4c730.png)
[_cuDNN.txt](https://github.com/lmb-freiburg/flownet2/files/1503231/_cuDNN.txt)

**Comment by nikolausmayer** [comment]
Hi,
I'd guess that it's a CuDNN version conflict... what version are you on? Our codebase should compile with CuDNN 5.

**Comment by Maryada-27** [comment]
As I have CUDA 9.0, CuDNN is v7.0

**Comment by nikolausmayer** [comment]
Yes, that sounds like it could be the problem. We might push fixes for newer CUDA/CuDNN versions at some point, but we do not have a schedule for this. I'm afraid you will have to fix it yourself :)

**Comment by Maryada-27** [comment]
Hi,

It was easy to fix. Its working fine with CuDNN v 7.0 and CUDA 9.0 as well

**Comment by duganchen** [comment]
No. Post the "easy" fix first.

**Comment by nikolausmayer** [comment]
I'm closing the issue since the original problem has been solved. @Maryada-27 feel free to post your fix if you want to ;)

**Comment by Maryada-27** [comment]
Hi,

I have replaced few files as suggestion in https://github.com/BVLC/caffe/issues/5868 and tagged links. 
[NewCUDNN.zip](https://github.com/lmb-freiburg/flownet2/files/1611878/NewCUDNN.zip)

**Comment by mrgransky** [comment]
@Maryada-27, I seriously love u <3 <3 cuz it is compiling now ....  :)
